# Generated by Django 5.0.2 on 2024-02-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Namiot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rozmiar", models.PositiveSmallIntegerField()),
                (
                    "kolor",
                    models.CharField(
                        choices=[
                            ("ZIELONY", "zielony"),
                            ("CZERWONY", "czerwony"),
                            ("NIEBIESKI", "niebieski"),
                        ],
                        default="CZERWONY",
                        max_length=16,
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("PREMIUM", "premium"),
                            ("OK", "ok"),
                            ("BUDGET", "budget"),
                        ],
                        default="OK",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rezerwacja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "namiot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rezerwacje.namiot",
                    ),
                ),
            ],
        ),
    ]
